apiVersion: v1
kind: ServiceAccount
metadata:
  name: spire-server
  namespace: spire
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spire-agent
  namespace: spire
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spire-root-agent
  namespace: spire
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oidc-provider
  namespace: oidc-provider
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spire-controller-manager
  namespace: spire
---
apiVersion: v1
kind: Secret
metadata:
  name: spire-controller-manager-token
  namespace: spire
  annotations:
    kubernetes.io/service-account.name: spire-controller-manager
type: kubernetes.io/service-account-token