apiVersion: v1
kind: Namespace
metadata:
  name: csi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spire-csi-provider
  namespace: csi
---
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/name: spire-csi-provider
  name: spire-csi-provider
  namespace: csi
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: spire-csi-provider
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spire-csi-provider
        spiffe.io/spire-managed-identity: "true"
    spec:
      serviceAccountName: spire-csi-provider
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: provider
          image: secrets-store-csi-provider-spire:v0.0.4
          imagePullPolicy: Never
          args:
            - -endpoint=/provider/spire.sock
            - -socketPath=/run/spire/agent-admin-sockets/child-01-admin.sock
            - -socketPath2=/run/spire/agent-admin-sockets/child-02-admin.sock
            - -logLevel=debug
            - -healthAddr=:8080
            - -metricsAddr=:8081
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - name: health
              containerPort: 8080
              protocol: TCP
            - name: metrics
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/live
              port: health
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: health
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 50m
              memory: 100Mi
          securityContext:
            privileged: true
          volumeMounts:
            - name: providervol
              mountPath: "/provider"
            - name: spire-agent-socket
              mountPath: "/run/spire/agent-sockets"
              readOnly: true
            - name: spire-admin-socket
              mountPath: "/run/spire/agent-admin-sockets"
              readOnly: true
      volumes:
        - name: providervol
          hostPath:
            path: "/etc/kubernetes/secrets-store-csi-providers"
        - name: spire-agent-socket
          hostPath:
            path: "/run/spire/agent-sockets"
            type: Directory
        - name: spire-admin-socket
          hostPath:
            path: "/run/spire/agent-admin-sockets"
            type: Directory