apiVersion: v1
kind: Namespace
metadata:
  name: app-a
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-workload-sa-a
  namespace: app-a
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: spire
  namespace: app-a
spec:
  provider: spire
  parameters:
    useCase: "mesh"
    trustDomain: "example.org"
    objects: |
      - objectName: "x509"
        type: "x509-svid"
        filePermission: 0640
        paths:
          - "x509/cert.pem"
          - "x509/key.pem"
          - "x509/bundle.pem"
      - objectName: "app1-jwt"
        type: "jwt-svid"
        filePermission: 0640
        audience:
          - "app1"
        paths:
          - "jwt/app1.token"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-workload-a
  namespace: app-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-workload-a
  template:
    metadata:
      labels:
        app: test-workload-a
        spiffe.io/spire-managed-identity: "true"
    spec:
      serviceAccountName: test-workload-sa-a
      containers:
        - name: test
          image: k8s.gcr.io/pause:3.9
          resources:
            requests:
              memory: "4Mi"
              cpu: "1m"
            limits:
              memory: "8Mi"
              cpu: "2m"
          volumeMounts:
            - name: spire-svids
              mountPath: "/run/spire"
              readOnly: true
      volumes:
        - name: spire-svids
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "spire"
