apiVersion: v1
kind: Service
metadata:
  name: spire-server
  namespace: spire
  labels:
    app: spire-server
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8081
      name: spire-server
    - port: 8080
      targetPort: 8080
      name: health
    - port: 8443
      targetPort: 8443
      name: federation
  selector:
    app: spire-server