apiVersion: v1
kind: ConfigMap
metadata:
  name: spire-root-agent
  namespace: spire
data:
  agent.conf: |
    agent {
      data_dir = "/run/spire"
      log_level = "DEBUG"
      server_address = "172.17.0.1"
      server_port = "30443"
      socket_path = "/run/spire/root-agent-sockets/socket"
      trust_bundle_path = "/run/spire/bundle/bundle.crt"
      trust_domain = "example.org"
    }

    plugins {
      NodeAttestor "k8s_psat" {
        plugin_data {
          cluster = "spire-subordinate-02"
          token_path = "/var/run/secrets/tokens/spire-root-agent"
        }
      }

      KeyManager "memory" {
        plugin_data = {}
      }

      WorkloadAttestor "k8s" {
        plugin_data {
          kubelet_secure_port = 10250
          skip_kubelet_verification = true
          disable_container_selectors = true
          node_name_env = "NODE_IP"
        }
      }

      WorkloadAttestor "unix" {
        plugin_data = {}
      }
    }